// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: op.proto

package refs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Oplog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ops []*Oplog_Op `protobuf:"bytes,1,rep,name=ops" json:"ops,omitempty"`
	// [oneof
	ObjPack []byte   `protobuf:"bytes,16,opt,name=obj_pack,json=objPack" json:"obj_pack,omitempty"`
	Objs    [][]byte `protobuf:"bytes,17,rep,name=objs" json:"objs,omitempty"`
	Params  []string `protobuf:"bytes,18,rep,name=params" json:"params,omitempty"` // oneof]
}

func (x *Oplog) Reset() {
	*x = Oplog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oplog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oplog) ProtoMessage() {}

func (x *Oplog) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oplog.ProtoReflect.Descriptor instead.
func (*Oplog) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{0}
}

func (x *Oplog) GetOps() []*Oplog_Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *Oplog) GetObjPack() []byte {
	if x != nil {
		return x.ObjPack
	}
	return nil
}

func (x *Oplog) GetObjs() [][]byte {
	if x != nil {
		return x.Objs
	}
	return nil
}

func (x *Oplog) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type Oplog_Op struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Target    []byte  `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	OldTarget []byte  `protobuf:"bytes,3,opt,name=old_target,json=oldTarget" json:"old_target,omitempty"`
}

func (x *Oplog_Op) Reset() {
	*x = Oplog_Op{}
	if protoimpl.UnsafeEnabled {
		mi := &file_op_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Oplog_Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oplog_Op) ProtoMessage() {}

func (x *Oplog_Op) ProtoReflect() protoreflect.Message {
	mi := &file_op_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oplog_Op.ProtoReflect.Descriptor instead.
func (*Oplog_Op) Descriptor() ([]byte, []int) {
	return file_op_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Oplog_Op) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Oplog_Op) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Oplog_Op) GetOldTarget() []byte {
	if x != nil {
		return x.OldTarget
	}
	return nil
}

var File_op_proto protoreflect.FileDescriptor

var file_op_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x65, 0x66, 0x73,
	0x22, 0x8c, 0x01, 0x0a, 0x05, 0x4f, 0x70, 0x6c, 0x6f, 0x67, 0x12, 0x1b, 0x0a, 0x03, 0x6f, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x66, 0x73, 0x2e, 0x4f,
	0x70, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x5f, 0x70,
	0x61, 0x63, 0x6b, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x0c, 0x0a, 0x04, 0x6f, 0x62, 0x6a,
	0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0c, 0x12, 0x0e, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x12, 0x20, 0x03, 0x28, 0x09, 0x1a, 0x36, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x0c, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x12, 0x0e, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x12, 0x12, 0x0a, 0x0a, 0x6f,
	0x6c, 0x64, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x42,
	0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69,
	0x75, 0x6b, 0x75, 0x6f, 0x2f, 0x72, 0x61, 0x67, 0x69, 0x74, 0x2f, 0x72, 0x65, 0x66, 0x73,
}

var (
	file_op_proto_rawDescOnce sync.Once
	file_op_proto_rawDescData = file_op_proto_rawDesc
)

func file_op_proto_rawDescGZIP() []byte {
	file_op_proto_rawDescOnce.Do(func() {
		file_op_proto_rawDescData = protoimpl.X.CompressGZIP(file_op_proto_rawDescData)
	})
	return file_op_proto_rawDescData
}

var file_op_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_op_proto_goTypes = []interface{}{
	(*Oplog)(nil),    // 0: refs.Oplog
	(*Oplog_Op)(nil), // 1: refs.Oplog.Op
}
var file_op_proto_depIdxs = []int32{
	1, // 0: refs.Oplog.ops:type_name -> refs.Oplog.Op
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_op_proto_init() }
func file_op_proto_init() {
	if File_op_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_op_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oplog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_op_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Oplog_Op); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_op_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_proto_goTypes,
		DependencyIndexes: file_op_proto_depIdxs,
		MessageInfos:      file_op_proto_msgTypes,
	}.Build()
	File_op_proto = out.File
	file_op_proto_rawDesc = nil
	file_op_proto_goTypes = nil
	file_op_proto_depIdxs = nil
}
